//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ObjectsID {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectsID() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.ObjectsID", typeof(ObjectsID).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.2021.4.6.0.
        /// </summary>
        public static string ID_AvailablePhysicalMemory {
            get {
                return ResourceManager.GetString("ID_AvailablePhysicalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.2021.4.5.0.
        /// </summary>
        public static string ID_PhysicalMemoryUsage {
            get {
                return ResourceManager.GetString("ID_PhysicalMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.4.0.
        /// </summary>
        public static string ID_SysContact {
            get {
                return ResourceManager.GetString("ID_SysContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.1.0.
        /// </summary>
        public static string ID_SysDescr {
            get {
                return ResourceManager.GetString("ID_SysDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.6.0.
        /// </summary>
        public static string ID_SysLocation {
            get {
                return ResourceManager.GetString("ID_SysLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.5.0.
        /// </summary>
        public static string ID_SysName {
            get {
                return ResourceManager.GetString("ID_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.25.1.6.0.
        /// </summary>
        public static string ID_SysNumProcesses {
            get {
                return ResourceManager.GetString("ID_SysNumProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.25.1.5.0.
        /// </summary>
        public static string ID_SysNumUsers {
            get {
                return ResourceManager.GetString("ID_SysNumUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.7.0.
        /// </summary>
        public static string ID_SysServices {
            get {
                return ResourceManager.GetString("ID_SysServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.2.1.1.3.0.
        /// </summary>
        public static string ID_SysUptime {
            get {
                return ResourceManager.GetString("ID_SysUptime", resourceCulture);
            }
        }
    }
}
