//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerData()
        {
            this.ServerResources = new HashSet<ServerResources>();
        }
    
        public int idServer { get; set; }
        public string sysDescr { get; set; }
        public string sysName { get; set; }
        public string sysLocation { get; set; }
        public string sysContact { get; set; }
        public string sysUpTime { get; set; }
        public string sysObjectID { get; set; }
        public int sysServices { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerResources> ServerResources { get; set; }
    }
}
