//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerResources
    {
        public int idResource { get; set; }
        public string name { get; set; }
        public string objectID { get; set; }
        public string value { get; set; }
        public int idServer { get; set; }
        public int sysServices { get; set; }
        public string sysUpTime { get; set; }
        public string sysDescr { get; set; }
        public string sysName { get; set; }
        public string sysLocation { get; set; }
        public string sysContact { get; set; }
    
        public virtual ServerData ServerData { get; set; }
    }
}
